favicon: null
name: Melanie
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0
  brandStrength: 0
  lightness: 1
  brandColors:
    - '#D8F2FF'
    - '#0A0D17'
    - '#A5C5D0'
    - '#38BCB4'
    - '#BD6C78'
  rhythmicContrast: 0
typography_spectrum: 0.8823845
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.3560687
analytics:
  twitter: null
  google: null
  facebook: null
